"use client";

import { motion } from "framer-motion";
import { BarChart3, FileText, Sparkles } from "lucide-react";

const CARDS = [
  {
    title: "ATS Report",
    subtitle: "Match score + role alignment",
    icon: BarChart3,
    lines: [
      "Match Score: 82/100",
      "Missing Keywords: 12",
      "Warnings: 3",
      "Strength: System Design",
    ],
  },
  {
    title: "Cover Letter Draft",
    subtitle: "Tailored in your tone",
    icon: FileText,
    lines: [
      "Opening optimized for the role",
      "Keywords woven naturally",
      "Impact-first middle paragraph",
      "Confident closing CTA",
    ],
  },
  {
    title: "Impact Bullets",
    subtitle: "Metric-first rewrites",
    icon: Sparkles,
    lines: [
      "Action verb upgrades",
      "Measurable outcomes",
      "Before/after improvements",
      "Recruiter-readable clarity",
    ],
  },
];

export default function HeroShowcase() {
  return (
    <div className="relative flex w-full items-center justify-center py-10">
      <div className="pointer-events-none absolute -inset-10 rounded-full bg-purple-500/10 blur-3xl" />

      <div className="relative h-[340px] w-[420px]">
        {CARDS.map((card, idx) => {
          const Icon = card.icon;
          const deck = [
            { x: -32, y: 36, r: -10, s: 0.94, z: 10, o: 0.65 },
            { x: 0, y: 10, r: 0, s: 1.0, z: 30, o: 1.0 },
            { x: 34, y: 44, r: 10, s: 0.94, z: 10, o: 0.65 },
          ][idx];

          const driftDuration = 6.2 + idx * 0.4;

          return (
            <motion.div
              key={card.title}
              initial={{ opacity: 0, y: 18 }}
              animate={{
                opacity: deck?.o ?? 1,
                x: [deck?.x ?? 0, (deck?.x ?? 0) + (idx === 1 ? 6 : 4), deck?.x ?? 0],
                y: [deck?.y ?? 0, (deck?.y ?? 0) - (idx === 1 ? 8 : 5), deck?.y ?? 0],
                rotate: [deck?.r ?? 0, (deck?.r ?? 0) + (idx === 1 ? 1.2 : 0.8), deck?.r ?? 0],
              }}
              transition={{
                opacity: { duration: 0.7, ease: "easeOut", delay: 0.15 + idx * 0.1 },
                x: {
                  duration: driftDuration,
                  ease: "easeInOut",
                  repeat: Infinity,
                  repeatType: "mirror",
                },
                y: {
                  duration: driftDuration,
                  ease: "easeInOut",
                  repeat: Infinity,
                  repeatType: "mirror",
                },
                rotate: {
                  duration: driftDuration + 0.6,
                  ease: "easeInOut",
                  repeat: Infinity,
                  repeatType: "mirror",
                },
              }}
              whileHover={{
                y: (deck?.y ?? 0) - 18,
                rotate: (deck?.r ?? 0) + 2,
                scale: (deck?.s ?? 1) + 0.02,
                opacity: 1,
                transition: { duration: 0.24, ease: "easeOut" },
              }}
              style={{ zIndex: deck?.z ?? 1 }}
              className="absolute left-1/2 top-1/2 w-[320px] -translate-x-1/2 -translate-y-1/2"
            >
              <div className="relative overflow-hidden rounded-xl border border-white/10 bg-white/[0.035] shadow-2xl shadow-black/35 backdrop-blur-md">
                <div className="pointer-events-none absolute inset-x-0 top-0 h-px bg-white/20" />
                <div className="pointer-events-none absolute -left-10 -top-10 h-40 w-40 rounded-full bg-purple-500/18 blur-3xl" />

                <div className="relative p-5">
                  <div className="flex items-start justify-between gap-3">
                    <div>
                      <p className="text-sm font-semibold text-white">{card.title}</p>
                      <p className="mt-0.5 text-xs text-white/55">{card.subtitle}</p>
                    </div>

                    <div className="flex h-9 w-9 items-center justify-center rounded-xl border border-white/10 bg-white/[0.03]">
                      <Icon className="h-4 w-4 text-white/80" />
                    </div>
                  </div>

                  <div className="mt-4 space-y-2">
                    {card.lines.map((line) => (
                      <div key={line} className="flex items-center gap-2">
                        <span className="h-1.5 w-1.5 rounded-full bg-white/25" />
                        <p className="text-xs text-white/70">{line}</p>
                      </div>
                    ))}
                  </div>

                  <div className="mt-5 flex items-center justify-between">
                    <p className="text-[11px] text-white/40">Generated by Tambo</p>
                    <p className="text-[11px] text-white/40">Kyber Studio</p>
                  </div>
                </div>
              </div>
            </motion.div>
          );
        })}
      </div>
    </div>
  );
}
